In [1]:
import pandas as pd

#### **Creating Two Separate Files for Newly Listed and Sold Properties**

##### Newly Listed Properties

##### 2024 Listings

In [4]:
'''
df_list = []
for i in range(1, 13):
    file_path = f"../data/Listing/CRMLSListing2024{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_list.append(df_listing)
  
df_listings_2024 = pd.concat(df_list, ignore_index=True)
'''

'\ndf_list = []\nfor i in range(1, 13):\n    file_path = f"../data/Listing/CRMLSListing2024{i:02d}.csv"\n\n    print(f"Reading file: {file_path}")\n    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")\n    df_list.append(df_listing)\n\ndf_listings_2024 = pd.concat(df_list, ignore_index=True)\n'

In [ ]:
# df_listings_2024['Year'] = 2024
# df_listings_2024.to_csv("../data/Listing/listed_transactions_2024.csv", index=False)

##### 2025 Listings

In [7]:
'''
df_list = []
for i in range(1, 13):
    file_path = f"../data/Listing/CRMLSListing2025{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_list.append(df_listing)
  
df_listings_2025 = pd.concat(df_list, ignore_index=True)
'''

'\ndf_list = []\nfor i in range(1, 13):\n    file_path = f"../data/Listing/CRMLSListing2025{i:02d}.csv"\n\n    print(f"Reading file: {file_path}")\n    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")\n    df_list.append(df_listing)\n\ndf_listings_2025 = pd.concat(df_list, ignore_index=True)\n'

In [ ]:
#df_listings_2025['Year'] = 2025
#df_listings_2025.to_csv("../data/Listing/listed_transactions_2025.csv", index=False)

##### 2026 Listings

In [11]:
'''
df_list = []
for i in range(1, 4):
    file_path = f"../data/Listing/CRMLSListing2026{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_list.append(df_listing)
  
df_listings_2026 = pd.concat(df_list, ignore_index=True)
'''

'\ndf_list = []\nfor i in range(1, 4):\n    file_path = f"../data/Listing/CRMLSListing2026{i:02d}.csv"\n\n    print(f"Reading file: {file_path}")\n    df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")\n    df_list.append(df_listing)\n\ndf_listings_2026 = pd.concat(df_list, ignore_index=True)\n'

In [ ]:
#df_listings_2026['Year'] = 2026
#df_listings_2026.to_csv("../data/Listing/listed_transactions_2026.csv", index=False)

##### 2024 to 2026 Listings

In [10]:
df_listings_2024 = pd.read_csv("../data/Listing/listed_transactions_2024.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\2195753770.py:1: DtypeWarning: Columns (0: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings_2024 = pd.read_csv("../data/Listing/listed_transactions_2024.csv", encoding="ISO-8859-1")

['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus', 'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1', 'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1', 'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict', 'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1', 'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1', 'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year']

In [11]:
df_listings_2025 = pd.read_csv("../data/Listing/listed_transactions_2025.csv", encoding="ISO-8859-1")

In [24]:
df_listings_2026 = pd.read_csv("../data/Listing/listed_transactions_2026.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\4126579556.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: ElementarySchool, 2: BuilderName, 3: BusinessType, 4: MiddleOrJuniorSchool) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings_2026 = pd.read_csv("../data/Listing/listed_transactions_2026.csv", encoding="ISO-8859-1")

In [28]:
df_listings = pd.concat([df_listings_2024, df_listings_2025, df_listings_2026], ignore_index=True)

In [29]:
df_listings.shape

(853754, 85)

In [30]:
df_listings['Year'].value_counts()

Year
2024    383920
2025    363315
2026    106519
Name: count, dtype: int64

In [ ]:
# df_listings.to_csv("../data/Listing/listed_transactions.csv", index=False)

In [59]:
df_listings = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")
df_listings.head()

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\974492464.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61,2024
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN,2024
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704,2024
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades,2024
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024

In [61]:
df_listings['Year'].value_counts()

Year
2024    383920
2025    363315
2026    106519
Name: count, dtype: int64

In [60]:
df_listings.shape

(853754, 85)

##### Closed/Sold Properties

##### 2024 Sold Listings

In [ ]:
'''
df_sold = []
for i in range(1, 13):
    file_path = f"../data/Sold/CRMLSSold2024{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_sold.append(df_selling)
  
df_sold_2024 = pd.concat(df_sold, ignore_index=True)
'''

Reading file: ../data/Sold/CRMLSSold202401.csv
Reading file: ../data/Sold/CRMLSSold202402.csv
Reading file: ../data/Sold/CRMLSSold202403.csv
Reading file: ../data/Sold/CRMLSSold202404.csv

C:\Users\mayab\AppData\Local\Temp\ipykernel_7676\987517719.py:6: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")

Reading file: ../data/Sold/CRMLSSold202405.csv
Reading file: ../data/Sold/CRMLSSold202406.csv
Reading file: ../data/Sold/CRMLSSold202407.csv
Reading file: ../data/Sold/CRMLSSold202408.csv
Reading file: ../data/Sold/CRMLSSold202409.csv
Reading file: ../data/Sold/CRMLSSold202410.csv
Reading file: ../data/Sold/CRMLSSold202411.csv
Reading file: ../data/Sold/CRMLSSold202412.csv

In [ ]:
#df_sold_2024['Year'] = 2024
#df_sold_2024.to_csv("../data/Sold/sold_transactions_2024.csv", index=False)

##### 2025 Sold Listings

In [ ]:
'''
df_sold = []
for i in range(1, 13):
    file_path = f"../data/Sold/CRMLSSold2025{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_sold.append(df_selling)
  
df_sold_2025 = pd.concat(df_sold, ignore_index=True)
'''

Reading file: ../data/Sold/CRMLSSold202501.csv
Reading file: ../data/Sold/CRMLSSold202502.csv
Reading file: ../data/Sold/CRMLSSold202503.csv
Reading file: ../data/Sold/CRMLSSold202504.csv
Reading file: ../data/Sold/CRMLSSold202505.csv
Reading file: ../data/Sold/CRMLSSold202506.csv

C:\Users\mayab\AppData\Local\Temp\ipykernel_7676\1639992141.py:6: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")

Reading file: ../data/Sold/CRMLSSold202507.csv
Reading file: ../data/Sold/CRMLSSold202508.csv
Reading file: ../data/Sold/CRMLSSold202509.csv
Reading file: ../data/Sold/CRMLSSold202510.csv
Reading file: ../data/Sold/CRMLSSold202511.csv
Reading file: ../data/Sold/CRMLSSold202512.csv

In [ ]:
# df_sold_2025['Year'] = 2025
#df_sold_2025.to_csv("../data/Sold/sold_transactions_2025.csv", index=False)

##### 2026 Sold Listings

In [29]:
'''
df_sold = []
for i in range(1, 4):
    file_path = f"../data/Sold/CRMLSSold2026{i:02d}.csv"
        
    print(f"Reading file: {file_path}")
    df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")
    df_sold.append(df_selling)
  
df_sold_2026 = pd.concat(df_sold, ignore_index=True)
'''

'\ndf_sold = []\nfor i in range(1, 4):\n    file_path = f"../data/Sold/CRMLSSold2026{i:02d}.csv"\n\n    print(f"Reading file: {file_path}")\n    df_selling = pd.read_csv(file_path, encoding="ISO-8859-1")\n    df_sold.append(df_selling)\n\ndf_sold_2026 = pd.concat(df_sold, ignore_index=True)\n'

In [47]:
# df_sold_2026['Year'] = 2026
# df_sold_2026.to_csv("../data/Sold/sold_transactions_2026.csv", index=False)

##### 2024 to 2026 Closed/Sold Listings

In [48]:
df_sold_2024 = pd.read_csv("../data/Sold/sold_transactions_2024.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\4106193620.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: OriginatingSystemName, 3: OriginatingSystemSubName, 4: BuyerAgencyCompensationType, 5: latfilled, 6: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_2024 = pd.read_csv("../data/Sold/sold_transactions_2024.csv", encoding="ISO-8859-1")

In [49]:
df_sold_2025 = pd.read_csv("../data/Sold/sold_transactions_2025.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\1935601661.py:1: DtypeWarning: Columns (0: WaterfrontYN, 1: latfilled, 2: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_2025 = pd.read_csv("../data/Sold/sold_transactions_2025.csv", encoding="ISO-8859-1")

In [50]:
df_sold_2026 = pd.read_csv("../data/Sold/sold_transactions_2026.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\3313316751.py:1: DtypeWarning: Columns (0: WaterfrontYN, 1: ListAgentEmail, 2: OriginatingSystemName, 3: OriginatingSystemSubName) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_2026 = pd.read_csv("../data/Sold/sold_transactions_2026.csv", encoding="ISO-8859-1")

In [53]:
df_sold_listings = pd.concat([df_sold_2024, df_sold_2025, df_sold_2026], ignore_index=True)

In [54]:
df_sold_listings['Year'].value_counts()

Year
2024    272491
2025    260104
2026     58520
Name: count, dtype: int64

In [ ]:
# df_sold_listings.to_csv("../data/Sold/sold_transactions.csv", index=False)

In [56]:
df_sold_listings = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")
df_sold_listings.head()

C:\Users\mayab\AppData\Local\Temp\ipykernel_13972\2392212637.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: WaterfrontYN, 3: ListAgentEmail, 4: OriginatingSystemName, 5: OriginatingSystemSubName, 6: BuyerAgencyCompensationType, 7: latfilled, 8: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_listings = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,Year
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024

In [58]:
df_sold_listings.shape

(591115, 85)

In [57]:
df_sold_listings['Year'].value_counts()

Year
2024    272491
2025    260104
2026     58520
Name: count, dtype: int64